name: Build and Deploy Lambda Functions

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  build-lambdas:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm run bootstrap

      - name: Build Lambda functions
        run: npm run build-lambdas

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lambda-artifacts
          path: deployments/artifacts/*.zip
          retention-days: 30

  deploy-infrastructure:
    needs: build-lambdas
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: lambda-artifacts
          path: deployments/artifacts/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install CDK dependencies
        run: npm install

      - name: Install CDK CLI globally
        run: npm install -g aws-cdk

      - name: Build CDK
        run: npm run build

      - name: Bootstrap CDK (if needed)
        run: cdk bootstrap --require-approval never

      - name: Deploy CDK Stack
        run: cdk deploy --require-approval never
